{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Authentication Attempts Per Minute",
   "type": "timeseries",
   "description": "Auth attempts per minute",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_login_success_total{source=\"jwt-pizza-service\"}[45s]) * 60",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_login_failure_total{source=\"jwt-pizza-service\"}[45s]) * 60",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Active Users Over Time",
   "type": "timeseries",
   "description": "Active users over time",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "activeUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "HTTP Requests per method per minute",
   "type": "timeseries",
   "description": "HTTP Requests per method per minute\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m])) * 60",
     "legendFormat": "ALL"
    }
   ]
  },
  {
   "title": "Request Latency over time",
   "type": "timeseries",
   "description": "Request latency across all endpoints",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_latency_count_total_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency over time",
   "type": "timeseries",
   "description": "Pizza Creation Latency over time",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pizza_latency_count_total_milliseconds{source=\"jwt-pizza-service\"}",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "gauge",
   "description": "CPU and memory percentage gauge",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percentage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percentage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Bitcoin Revenue per minute",
   "type": "stat",
   "description": "Bitcoin revenue per minute",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_BTC_total{source=\"jwt-pizza-service\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Requests per minute",
   "type": "timeseries",
   "description": "Pizza Requests success and failure per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_success_total{source=\"jwt-pizza-service\"}[50s]) * 60",
     "legendFormat": "success"
    },
    {
     "expr": "rate(pizza_purchase_failure_total{source=\"jwt-pizza-service\"}[50s]) * 60",
     "legendFormat": "failure"
    }
   ]
  }
 ]
}